INCLUDE_SFXS=lib.la.so.sa.a.sl
IMPLICIT_TARGETS=src/string_to_integer.o
BUILD_SIGNATURE=1460270381,1760
META_DEPS=/usr/bin/gccsrc/print_number.cusersrc/holbertonschool.h
COMMAND=@echo " The compiler gcc now is creating the object:  src/string_to_integer.o"@gcc -Wall -pedantic -Werror -Wextra -Iinc/. -c src/print_number.c -o src/string_to_integer.o
SORTED_DEPS=src/absolute.csrc/cap_string.csrc/contact_strings.csrc/first_digit.c/usr/bin/gccinc/holbertonschool.hsrc/is_prime_number.csrc/lowercase.csrc/nconcat_strings.csrc/positive_or_not.csrc/power.csrc/print_array.csrc/print_number.csrc/print_string.csrc/reverse_array.csrc/reverse_string.csrc/square_root.csrc/str_len.csrc/string_copy.csrc/string_ncopy.csrc/string_to_integer.csrc/strings_compare.csrc/swap_int.csrc/uppercase.csrc/uppercase_string.c
SIG_METHOD_NAME=C
ARCH=x86_64-linux-gnu-thread-multi
CWD=..
IMPLICIT_DEPS=
DEP_SIGS=X+ZBQjHg43Gm2Fv+JFpeAwdQrJY8nrqob1CB5E6ThirAU3/cyKjsMbNk3UDwMCS4Qwf1w86vkVkD0MZays1INN7w1453880441,775888wNnEIkEp81UUKY1htfjJqwNonO4ZiXkzdUU8VBldez2gceRL76SqqRDMa38nTCgBCw79PVVXti1pw4arDWzBv/yQ90JCrc6OeW/G5ZVNDca6Xg2k9t2Vbrd+u2Ow7gjGW8sw6REW4lZlWz1rL8b9V8N8uQgaDAmPmN9pyj9JhrZf+S6Aj+6XpchZU6hNDx4s73N/dA57HLG/FdmIxY/uRpV+DTbw0qLGVwG1sKTmP3vzwxvADAZ/o5kq+ZY8vcsB5NiPNjhAz8fETP9x9lJ1v65lS3S+qgQh+prMU+FXG2UmBoW7H4lQrQ0JaFV3VOBzSAZOBxHviwZkClzwxHgqKZZlfiGhDl5w+5muEpT1kbKswogPuH36KgkivJ8xkp6RsZFbZdgkRoIwcjgdr/YrkqkxUyetB/4M0wrKRJT3yqjlL5DppEL8pQZg
INCLUDE_PATHS=sysinc/./usr/local/include/usr/includeuserinc/./usr/local/include/usr/include
SIGNATURE=1460270381,1760
SIG_METHOD_IMPLICIT=1
END=